AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./controllers
      Handler: main.handler
      Runtime: python3.10
      Events:
        HttpAny:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: '/{proxy+}'
            Method: any
      Layers: 
        - !Ref MyLayer
      Policies: # use Policies property
      - AWSLambdaBasicExecutionRole # allow writing logs to CloudWatch
      - AWSLambdaRole # allow API Gateway to invoke your function
  MyLayer:
    Type: AWS::Serverless::LayerVersion # use AWS SAM layer version
    Properties:
      ContentUri: ./my_layer # use ContentUri property
      CompatibleRuntimes:
        - python3.10
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FastAPIIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FastAPIFunction.Arn